"""empty message

Revision ID: 26f4cf4ea172
Revises: 0002
Create Date: 2026-07-10 20:00:05.081757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26f4cf4ea172'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boosts', 'ap_id',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.drop_index('ix_follows_follower_following', table_name='follows')
    op.alter_column('keyword_mutes', 'keyword',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('likes', 'ap_id',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('likes', 'reaction',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.drop_index('ix_notif_user_created', table_name='notifications')
    op.drop_index('ix_notif_user_type', table_name='notifications')
    op.alter_column('novels', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.create_foreign_key(None, 'pending_deliveries', 'users', ['sender_id'], ['id'])
    op.alter_column('posts', 'ap_id',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('posts', 'in_reply_to_ap_id',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('posts', 'poll_data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.drop_index('ix_posts_ap_id', table_name='posts')
    op.drop_index('ix_posts_author_created', table_name='posts')
    op.drop_index('ix_posts_author_deleted_created', table_name='posts')
    op.alter_column('processed_activities', 'id',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=1024),
               existing_nullable=False)
    op.alter_column('server_settings', 'enable_reactions',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'moved_to',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=True,
               existing_server_default=sa.text('("")'))
    op.drop_column('users', 'series_default_visibility')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('series_default_visibility', sa.VARCHAR(length=16), nullable=True))
    op.alter_column('users', 'moved_to',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('("")'))
    op.alter_column('server_settings', 'enable_reactions',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('processed_activities', 'id',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    op.create_index('ix_posts_author_deleted_created', 'posts', ['author_id', 'is_deleted', 'created_at'], unique=False)
    op.create_index('ix_posts_author_created', 'posts', ['author_id', 'created_at'], unique=False)
    op.create_index('ix_posts_ap_id', 'posts', ['ap_id'], unique=False)
    op.alter_column('posts', 'poll_data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('posts', 'in_reply_to_ap_id',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('posts', 'ap_id',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.drop_constraint(None, 'pending_deliveries', type_='foreignkey')
    op.alter_column('novels', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.create_index('ix_notif_user_type', 'notifications', ['user_id', 'notification_type'], unique=False)
    op.create_index('ix_notif_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.alter_column('likes', 'reaction',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('likes', 'ap_id',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('keyword_mutes', 'keyword',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.create_index('ix_follows_follower_following', 'follows', ['follower_id', 'following_id'], unique=False)
    op.alter_column('boosts', 'ap_id',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###
