"""Initial baseline

Revision ID: 29696bcd0cf9
Revises: 0006
Create Date: 2026-07-13 08:37:23.349814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29696bcd0cf9'
down_revision: Union[str, Sequence[str], None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_follows_follower_following', table_name='follows')
    op.drop_index('ix_notif_user_created', table_name='notifications')
    op.drop_index('ix_notif_user_type', table_name='notifications')
    op.drop_index('ix_posts_author_created', table_name='posts')
    op.drop_index('ix_posts_author_deleted_created', table_name='posts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_posts_author_deleted_created', 'posts', ['author_id', 'is_deleted', 'created_at'], unique=False)
    op.create_index('ix_posts_author_created', 'posts', ['author_id', 'created_at'], unique=False)
    op.create_index('ix_notif_user_type', 'notifications', ['user_id', 'notification_type'], unique=False)
    op.create_index('ix_notif_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_follows_follower_following', 'follows', ['follower_id', 'following_id'], unique=False)
    # ### end Alembic commands ###
