"""initial

Revision ID: b4c23ee6c9f3
Revises: 
Create Date: 2026-07-09 05:41:35.252106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4c23ee6c9f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_custom_emojis_keyword'), 'custom_emojis', ['keyword'], unique=False)
    op.alter_column('keyword_mutes', 'keyword',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.drop_column('users', 'is_pinned')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_pinned', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
    op.alter_column('keyword_mutes', 'keyword',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.drop_index(op.f('ix_custom_emojis_keyword'), table_name='custom_emojis')
    # ### end Alembic commands ###
